---
title           : "Morphological differences in Leptograpsus rock crabs using MANOVA and PCA."

shorttitle      : "Morphological differences in Leptograpsus rock crabs"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Abi Brown
    affiliation : 1

affiliation:
  - id          : 1
    institution : University of British Columbia


output: prereg::prereg_pdf
bibliography: references.bib
---

# Study Information

## Morphological differences in Leptograpsus rock crabs using MANOVA and PCA.

`r rmarkdown::metadata$title`

## Description

This project will explore the potential differences in morphology in two colour morphs of the rock crab *Leptograpsus variegatus* using data collected by @campbell1974.

## Hypotheses

The blue and orange colour morphs of *Leptograpsus variegatus* will exhibit significant differences in their morphological features beyond the blue/orange colour differentiation.

# Design Plan

## Study type

**Observational Study**.

## Study design

We have a factorial design with two factors (sex and colour morph) each with two levels (male/female and blue/orange).

# Sampling Plan

## Existing data

**Registration following analysis of the data**. As of the date of submission, I have accessed the full dataset and have visually examined the distribution of the variables (histograms).

## Explanation of existing data

In accessing the data, I have only completed simple visualizations of data distributions (histograms). I have only read through the introduction and data collection procedures of @campbell1974.

## Data collection procedures

Samples were collected in western Australia (Fremantle, W.A. (32"S., 117"E.) and measurements were taken with vernier calipers, accurate to the nearest 0.1mm [@campbell1974].

## Sample size

For each colour morph, 50 male and 50 female individuals were collected for a total of 200 individuals.

## Sample size rationale

@campbell1974 do not provide a reasoning for sample size selected. Additional data for these populations from other data sources was not found due to time constraints and lack of open availability.

# Variables

## Measured variables

Measured variables include:

| variable          | unit | type        |
|-------------------|------|-------------|
| sex               | \-   | categorical |
| colour morph      | \-   | categorical |
| frontal lobe size | mm   | continuous  |
| rear width        | mm   | continuous  |
| carapace length   | mm   | continuous  |
| carapace width    | mm   | continuous  |
| body depth        | mm   | continuous  |

# Analysis Plan

## Statistical models

A multivariate analysis of variance will be used to determine if significant differences in morphology exist between the blue/orange colour morphs or male/female sexes.

## Exploratory analyses

We anticipate that the colour morphs will exhibit differences in body shape and/or size, or in the relationship between morphological traits. A principal components analysis of the crabs morphological trait data will be used to explore potential morphological differences between colour morphs and/or sexes in multivariate space.

## Transformations

Based on initial examination of the data, no transformations are planned.

## Inference criteria

Significance of MANOVA tests will be determined using a significance values of p \> 0.005 for the F-test statistic.

Principal components will be kept or discarded based on the Kaiser-Guttman criterion which suggests retaining components with eigenvalues \>1.

## Data exclusion

No samples will be excluded from the analysis.

## Missing data

Data is complete as all observations have values for each measured variable.

# References

```{=tex}
\vspace{-2pc}
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{-1in}
\setlength{\parskip}{8pt}
```
\noindent
